---
deployment:
	tasks:
    #- export DEPLOYPATH=/home/uguiw0obdr4e/public_html/dimitril.com
    - export DEPLOYPATH=/home/uguiw0obdr4e/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp CHANGE.md $DEPLOYPATH
